apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-ui-1
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: guestbook-ui-1/staging
    repoURL: 'https://github.com/asad-abdullah/argo-app-of-apps-kustomize.git'
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true