apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- guestbook-ui-config.yaml
- guestbook-ui-deployment.yaml
- guestbook-ui-secret.yaml
- guestbook-ui-service.yaml